### ISSUE TITLE
Dismantle the LAMP servers

### ISSUE THREAD

**Issue by celskeggs** [sipb/machine-room#10]
We still have the CDs, the CD changers, and other hardware. We would like to reclaim the space in the server room, so we should take care of this.

We've had various people offer to make this happen, but no one has gotten it done.

**Comment by mcy** [comment]
Most recently, @emmakbat has been looking into doing this. I know that she's spoken to SAO about performing a sale.

**Comment by celskeggs** [comment]
@emmakbat what's the status of this?

**Comment by emmakbat** [comment]
I've ordered CD sleeves. Since I don't have SMR access I'd like to move at least one of the CD changers into the office so I can work on it but I'm not sure how to safely cut their power and remove them from the rack

**Comment by celskeggs** [comment]
I think you can just unplug them.

Let me know if you need help getting access?

**Comment by celskeggs** [comment]
I believe this has long since been accomplished, so closing this issue.
