### ISSUE TITLE
Renumber remaining UPSes

### ISSUE THREAD

**Issue by celskeggs** [sipb/machine-room#19]
I need to determine how to renumber the following UPSes:

- ~childrens-television-workshop~
- enron-energy-services
- alabama-power

This is dangerous, because doing this incorrectly can easily cause load to be dropped.

This involves:

1. Determine the models and vendors of these devices.
2. Find instruction manuals for them online.
3. Confirm renumbering plans with -c sipb.
4. Renumber them.

**Comment by celskeggs** [comment]
Additional information from zephyr:

 - ctw should be easy, via the web interface
 - quentin & asedeno were not able to get an IP configuration menu on the network cards' serial ports for ap and ees. They tried "Serial Port 2", which is actually an RS-232 port (19200 baud), not a DB9 port.
 - They also couldn't find the model number of the relevant card.
 - ap and ees don't ping, and may have never been renumbered off of the historical Ops network from when IS&T was still I/S.
 - The cables on ap and ees may be disconnected; it is unclear. There are no link lights.
 - jweiss believes that ap and ees have APC brand UPS cards, but we don't know anything further.
 - The management cards may need to be reset in order to talk over the serial port.

**Comment by celskeggs** [comment]
ctw requires old cipher suites, and I can't find any browser that supports them, so I wasn't able to update its IP yet.

EDIT: I'm recommended to try Cortana's IE installation.

**Comment by asedeno** [comment]
ctw has been migrated using Firefox on an Ubuntu 14.04 live image.

**Comment by celskeggs** [comment]
Not particularly critical compared to other UPS work to be done, which is likely to be invalidate this. Closing.
